# Generated by Django 4.1.3 on 2022-11-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="text",
            new_name="label",
        ),
        migrations.AddField(
            model_name="todo",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
