# Generated by Django 4.1.3 on 2022-11-26 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0002_rename_text_todo_label_todo_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="label",
            new_name="title",
        ),
    ]
